### ISSUE TITLE
Change variable declation syntax from `misal` to `ada`

### ISSUE THREAD

**Issue by rmdwirizki** [pveyes/naskah#12]
It's shorter and more explicit. Just my 2 cents. 

from
```
misal x = 4;
misal y = x;
```
to
```
ada x = 4;
ada y = x;
```

**Comment by pveyes** [comment]
The reason of using `misal` instead of other options is that it's a literal translation from `let`.

In this project, the goal is not to have shortest syntax as possible because the target audience is people who just started to learn programming, thus brevity is not necessary. Besides, `misal` is as long as `const` (both have 5 chars), the difference being the latter only have 1 vocal so it _sounds_ shorter.

I'm open for any suggestion, but personally I don't think `ada` is the right replacement

**Comment by rmdwirizki** [comment]
I see, thats rather clear, I agree with you at some points.. this is just my personal opinion though.
